### PR TITLE
linux-4.0.0 - latest PKGBUILD

### PR DESCRIPTION
**Pull request by Leryan**

### CODE REVIEW

**Comment by twelveeighty** [comment]
Hey, thanks for the patch! I'll pull it in as soon as 4.0.0 hits [testing], OK?

**Comment by Leryan** [comment]
Why waiting testing? DKMS is here to give the ability to every one to build its own kernel, even detached from Arch repos. Is it for testing purpose?

**Comment by twelveeighty** [comment]
Have you tested this against both the current Arch mainline (3.19.2 at the moment) and 4.0.0? If so, I can adopt it, but if not, I will need to have others test it first.

**Comment by Leryan** [comment]
Yes it is tested.

The only lines I really modified are for the compatibility with kernel 4.0, the other diff in the patch file are because the patch file was outdated here.

**Comment by twelveeighty** [comment]
Ah.. rats. I just realized I didn't push my local repository changes for the current release after all the commotion with the kernel panics. I'll have to do some some housekeeping first here.

**Pull request merged**
